# Generated by Django 4.2.2 on 2023-07-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userprofile_member1_class_userprofile_member1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='competition_id',
            field=models.IntegerField(default=0),
        ),
    ]
